#!/usr/bin/env node

var exec = require('child_process').exec,
    fs = require('fs'),
    chokidar = require('chokidar');

var folder = process.cwd();
var file = process.argv[2];

if (file.slice(-4) != ".elm") {
  throw "File must be an elm file.";
}

var source = folder + "/" + file;
var destination = source.slice(0, -4) + ".js";

console.log("Watching: ", file);

require('chokidar').watch(folder, {ignored: /(node_modules|elm-stuff)/}).on('all', function(event, path) {
  if ((event == "add" || event == "change") && path.slice(-4) == ".elm") {
    compile(source, destination);
  }
});

function compile(source, destination) {
  console.log("Compiling...", source)
  exec("elm-make --yes --output " + destination + " " + source, function(error, stdout, stderr) {
    var content;
    if (stderr){
      content = 'document.write(\"<pre style=\\\"position:fixed; top: 0; left: 0; right: 0; max-height: 80%; padding: 20px; overflow: auto; background: #fff; border-bottom: 4px solid red; z-index: 9999;\\\">'+stderr.replace(/\n/g, '\\n')+'</pre>\");';
      // Let's override the target file, with the error in it so that we don't have to watch the terminal
      fs.writeFile(destination, content, function(err) {
        if(err) {
          console.log("!!!", err);
        } else {
          console.log(stderr);
        }
      });
    }
    console.log(destination, " written");
  });

}

